title: Your awesome title
author: GitHub User
email: sylvia@Syl-create.github.com
theme : minima
description: > # this means to ignore newlines until "baseurl:"
  # Welcome to my blog

I'm glad you are here. I plan to talk about ...
Hello, everyone. I'm glad you are here. 
How are you? I hope you all fine. 
I plan to talk about how to build my artwork print blog.
Today I'm still working at home and I want to introduce you to my artwork design. 
I love colors and do some experiments with some app that already out there, like Canva, and Canvas.
I create my artwork combine with digital technic and traditional. The artwork print on apparel, accessories, and room decor.
To make my artwork design worthy, and I put them in my store online. 
So, if you want to know what it looks like, you can find it on my Pinterest (https://id.pinterest.com/sylviapessy1/)  and please follow me if you like it:)
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: https://twitter.com/sylvia_Yuchinta/ # DO NOT include the @ character, or else the build will fail!
github_username: https://github.com/Syl-create/ # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
